version: '3.7'
services:
  backend:
    build: /backend
    ports:
      - 3000:3000
    # volumes:
    #   - /backend:/backend
  # frontend:
  database:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongoDB
    volumes: 
    - ~/mongo/data:/data/db
networks:
  gym: