version: '3.7'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/backend
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
networks:
  gym: